Debug CI Github actions

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -9,7 +9,17 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Set up Git repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
+      - name: Ensure package.json is present
+        run: |
+          if [ ! -f "package.json" ]; then
+            echo "Error: package.json not found."
+            exit 1
+          fi
+
+      - name: Print package.json content
+        run: cat package.json
+
       - name: Set up Node version
         uses: actions/setup-node@v4
         with:
